### ISSUE TITLE
Same order of wildcards in spring as in prealignment.

### ISSUE THREAD

**Issue by zezzipa** [hydra-genetics/compression#19]
<!--
# hydra_genetics/compression
 feature request

Same order of wildcards in spring as in prealignment.
prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1.fastq.gz
while spring files becomes:
compression/spring/{sample}_{flowcell}_{lane}_{barcode}_{type}.spring

**Comment by padraicc** [comment]
https://github.com/hydra-genetics/compression/pull/20
